name: Build and Create JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Archive JAR file
      uses: actions/upload-artifact@v2
      with:
        name: my-jar
        path: target/my-java-project-1.0-SNAPSHOT.jar
